export const Vacancies = [
  {
    name: "Content Writer",
    preview: "Content Writer",
    status: "open",
    type: "Full-time",
    location: "Remote",
    uid: "cw00_",
    prologue:
      "A YouTube content writer is responsible for creating engaging and informative written content for YouTube videos",
    company: "Vowatex",
    desc: "A YouTube content writer, also known as a YouTube video description writer, is responsible for creating engaging and informative written content for YouTube videos. We are seeking a talented and creative Content Writer to join our team. You will collaborate with our creative teams to bring our brand and ideas to life through innovative and compelling visuals.",
    duties: [
      "Writing video descriptions: They craft compelling and engaging descriptions for YouTube videos that provide viewers with essential information about the video's content and help them understand what to expect.",
      "Creating engaging content: The content writer is responsible for developing content that captures the audience's attention, educates them, and encourages them to take action.",
      "Understanding YouTube algorithms: They need to be familiar with YouTube's algorithms and best practices to optimise their content for better visibility and reach.",
      "Collaborating with teams: Content writers often work with video producers, directors, and other team members to ensure that the written content aligns with the video's vision and goals.",
      "Managing multiple projects: They need to be able to handle multiple projects simultaneously and meet deadlines to ensure the timely delivery of high-quality content.",
      "Revising and editing content: Content writers are responsible for revising and editing their work to ensure it is error-free and aligns with the client's or company's standards.",
      "Researching and staying updated: They need to conduct in-depth research on industry topics and trends, as well as stay current on YouTube and video production best practices.",
    ],
    requirements: [
      "Proven experience as a content writer, preferably with a focus on YouTube scripts.",
      "Strong understanding of YouTube best practices and trends",
      "Exceptional writing and editing skills with a keen eye for detail.",
      "Ability to work collaboratively in a fast-paced environment.",
      "Excellent research skills and a commitment to accuracy.",
      "Familiarity with SEO best practices is a plus.",
    ],
    qualifications: [
      "Bachelor's degree in English, Journalism, Communications, or a related field.",
      "Proven experience as a content writer, with a strong portfolio showcasing YouTube video descriptions and scripts.",
      "Excellent command of the English language, with exceptional writing, editing, and proofreading skills.",
      "Strong understanding of YouTube algorithms, SEO, and best practices for creating engaging video content.",
      "Ability to conduct thorough research and stay up-to-date with industry trends and developments.",
      "Excellent organizational and time management skills, with the ability to handle multiple projects simultaneously and meet tight deadlines.",
      "Strong collaboration and communication skills, with the ability to work effectively with cross-functional teams.",
    ],
    process:
      "Join us on our exciting journey to create videos that will hook viewers, keep them engaged, and get the best channel push. And be a key player in shaping our content strategy! We look forward to welcoming a creative and talented Content Writer to our team. We would be delighted to hear from you if you are a talented and driven Graphic Designer looking to contribute to the growth of our business. To olaoluwamalachi@gmail, kindly send your résumé, cover letter, and a link to your portfolio featuring your best work. The above mentioned could also be done with the form below",
  },
  {
    name: "Video Editor",
    preview: "Video Editor",
    status: "closed",
    type: "Full-time (P.B.)",
    location: "Remote",
    uid: "ve01",
    prologue:
      "We are seeking Multiple creative and skilled Video Editors to join our dynamic team.",
    company: "Vowatex",
    desc: "As a Video Editor, you will be responsible for assembling and editing raw footage to create compelling videos that align with our requirements and details. The ideal candidate should have a keen eye for detail, strong storytelling abilities, and proficiency in video editing software.",
    duties: [
      "YouTube video editing - Edit and assemble footage with the Voice Over, ensuring the logical sequencing and smooth running of the final product",
      "Collaborate with the creative team to understand project requirements and objectives",
      "Add music, dialogue, graphics, and effects to enhance the video's impact",
      "Review and edit content for quality and consistency.",
      "Stay updated on industry trends and advancements in YouTibevideo editing techniques",
    ],
    requirements: [
      "Daily Work Availability and Very Fast Delivery",
      "Portfolio showcasing previous video editing work.",
      "Bachelor's degree in Film Studies, Media, or relevant field (preferred).",
      "Knowledge of motion graphics and animation is a plus.",
    ],
    qualifications: [
      "YouTube video editing experience.",
      "Proven experience as a Video Editor or similar role",
      "Proficiency in video editing software e.g., Adobe Premiere Pro (Preferred), Filmora, CapCut.",
      "Strong understanding of storytelling and visual composition.",
      "Excellent communication and teamwork skills.",
      "Ability to meet deadlines and work well under pressure.",
    ],
    process:
      'Interested candidates should submit their resume, cover letter, and a link to their portfolio to [info@miraldscale.com]. Please include "Video Editor Application" in the subject line. The above mentioned could also be done with the form below',
  },
];
